#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/dotEnvLoader.php';
dotEnvLoader(__DIR__ . '/.env');

use Milanmadar\CoolioORM;
use Symfony\Component\Console\Application;

// Create the Console app
$application = new Application();

// Register commands
$application->add(new CoolioORM\Command\ScaffoldCommand( CoolioORM\ORM::instance() ));

// Run it the console app
$application->run();
